import dayjs from 'dayjs'
import { Inbox } from 'lucide-react'

import { SectionCard } from '@/components/kit'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { formatMoney, formatPercent } from '@/utils/format'
import type { TradeIntent } from '@/types'

interface Props {
  intents: TradeIntent[]
  onApprove: (id: string) => void
  onReject: (id: string) => void
  onExecute: (id: string) => void
}

function statusVariant(status: string): 'default' | 'secondary' | 'outline' | 'destructive' {
  if (status === 'executed' || status === 'approved') return 'default'
  if (status === 'rejected' || status === 'failed') return 'destructive'
  if (status === 'executing') return 'secondary'
  return 'outline'
}

export function IntentQueue({ intents, onApprove, onReject, onExecute }: Props) {
  return (
    <SectionCard
      title="Execution Queue"
      description="Review before broker execution"
    >
      <p className="mb-4 text-xs text-muted-foreground">
        Intents are generated by an agent run. <span className="font-mono">proposed</span> means review pending,{' '}
        <span className="font-mono">approved</span> means ready to execute, and{' '}
        <span className="font-mono">executing/executed</span> reflect broker submission state.
      </p>

      {intents.length === 0 ? (
        <div className="flex flex-col items-center gap-2 py-10 text-center">
          <Inbox className="size-5 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">No intents in the queue. Run the agent to generate trades.</p>
        </div>
      ) : (
        <div className="flex flex-col gap-3">
          {intents.map((intent) => {
            const actionable = intent.status === 'proposed' || intent.status === 'approved'
            return (
              <div
                key={intent.id}
                className="flex flex-col gap-3 rounded-lg border border-border/60 bg-muted/20 p-4"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge variant={intent.side === 'buy' ? 'default' : 'destructive'}>
                      {intent.side.toUpperCase()}
                    </Badge>
                    <span className="font-medium">{intent.symbol}</span>
                    <span className="font-mono text-xs text-muted-foreground tabular-nums">
                      {intent.quantity.toFixed(4)} qty
                    </span>
                    {intent.account_kind && (
                      <Badge variant="outline" className="text-[10px] font-normal">
                        {intent.account_kind === 'stocks_isa' ? 'ISA' : 'Invest'}
                      </Badge>
                    )}
                  </div>
                  <Badge variant={statusVariant(intent.status)}>{intent.status}</Badge>
                </div>

                <p className="text-sm text-muted-foreground">{intent.rationale}</p>

                <div className="flex flex-wrap gap-x-5 gap-y-1 text-xs text-muted-foreground">
                  <span>
                    Edge{' '}
                    <span className="font-mono text-foreground tabular-nums">{formatPercent(intent.expected_edge)}</span>
                  </span>
                  <span>
                    Confidence{' '}
                    <span className="font-mono text-foreground tabular-nums">{formatPercent(intent.confidence)}</span>
                  </span>
                  <span>
                    Risk{' '}
                    <span className="font-mono text-foreground tabular-nums">{formatPercent(intent.risk_score)}</span>
                  </span>
                  <span>
                    Notional{' '}
                    <span className="font-mono text-foreground tabular-nums">
                      {formatMoney(intent.estimated_notional, 'GBP')}
                    </span>
                  </span>
                  <span className="font-mono tabular-nums">{dayjs(intent.created_at).format('MMM D HH:mm')}</span>
                </div>

                {intent.failure_reason && (
                  <p className="text-xs text-negative">{intent.failure_reason}</p>
                )}

                <div className="flex items-center justify-end gap-2">
                  <Button variant="ghost" size="sm" onClick={() => onReject(intent.id)} disabled={!actionable}>
                    Reject
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => onApprove(intent.id)} disabled={!actionable}>
                    Approve
                  </Button>
                  <Button size="sm" onClick={() => onExecute(intent.id)} disabled={!actionable}>
                    Execute
                  </Button>
                </div>
              </div>
            )
          })}
        </div>
      )}
    </SectionCard>
  )
}
