import dayjs from 'dayjs'

import type { TradeIntent } from '../types'

interface Props {
  intents: TradeIntent[]
  onApprove: (id: string) => void
  onReject: (id: string) => void
  onExecute: (id: string) => void
}

function pct(v: number) {
  return `${(v * 100).toFixed(1)}%`
}

export function IntentQueue({ intents, onApprove, onReject, onExecute }: Props) {
  return (
    <section className="glass-card intents-card">
      <div className="section-heading-row">
        <h2>Execution Queue</h2>
        <span className="hint">Review before broker execution</span>
      </div>
      <p className="muted queue-help">
        Intents are generated by an agent run. `proposed` means review pending, `approved` means ready to execute,
        and `executing/executed` reflect broker submission state.
      </p>
      <div className="intents-list intent-scroll">
        {intents.length === 0 && <p className="muted">No intents yet. Run agent.</p>}
        {intents.map((intent) => (
          <article key={intent.id} className="intent-item">
            <div className="intent-head">
              <div>
                <span className={`pill ${intent.side}`}>{intent.side.toUpperCase()}</span>
                <strong>{intent.symbol}</strong>
                <span className="muted">{intent.quantity.toFixed(4)} qty</span>
              </div>
              <span className={`status ${intent.status}`}>{intent.status}</span>
            </div>
            <p>{intent.rationale}</p>
            <div className="intent-metrics">
              <span>Edge {pct(intent.expected_edge)}</span>
              <span>Confidence {pct(intent.confidence)}</span>
              <span>Risk {pct(intent.risk_score)}</span>
              <span>Notional ${intent.estimated_notional.toFixed(2)}</span>
              <span>{dayjs(intent.created_at).format('MMM D HH:mm')}</span>
            </div>
            <div className="intent-actions">
              <button className="btn ghost" onClick={() => onReject(intent.id)} disabled={intent.status !== 'proposed' && intent.status !== 'approved'}>
                Reject
              </button>
              <button className="btn ghost" onClick={() => onApprove(intent.id)} disabled={intent.status !== 'proposed' && intent.status !== 'approved'}>
                Approve
              </button>
              <button
                className="btn primary"
                onClick={() => onExecute(intent.id)}
                disabled={!['approved', 'proposed'].includes(intent.status)}
              >
                Execute
              </button>
            </div>
            {intent.failure_reason && <p className="error-text">{intent.failure_reason}</p>}
          </article>
        ))}
      </div>
    </section>
  )
}
